export const fieldofstudy = [
  "Accounting and Finance",
  "Animal Science",
  "Anthropology",
  "Agricultural Sciences",
  "Applied Economics and Manangement",
  "Archeology",
  "Architecture",
  "Astronomy",
  "Biological Engineering",
  "Biological Science",
  "Business Management",
  "Chemical Engineering",
  "Communication",
  "Computer Science",
  "Economics",
  "Electrical and Computer Engineering",
  "English",
  "Enviromental Enginerring",
  "Food Science",
  "Global and Public Health Science",
  "Human Administration",
  "Human Resource",
  "ICT and Information Technology",
  "Marketing",
  "Mechanical Engineering",
  "Physics",
  "Political Science",
  "Psychology",
  "Software Engineering",
  "Sport Science",
  "other",
];
