export const profession = [
  "Accounting and Finance",
  "Admin,Secretiarial and Clerical",
  "Agriculture",
  "Automotive",
  "Banking and inssurance",
  "Biotech and Pharamaceutical",
  "Business and Management",
  "Business Development",
  "Consultancy and Traning",
  "Customer service",
  "Development and project managment",
  "Economics",
  "Engineering and Construction",
  "Health Care",
  "Human Resource",
  "Information Technology",
  "Inventory and Stock",
  "Logostics and Transport",
  "Management",
  "Manufacturing",
  "Sales and Marketing",
  "Media and Journalism",
  "Enviroment and Natural Resource",
  "Natural Sciences",
  "Purchasing and Procurement",
  "Quality Assurance",
  "Science and Technology",
  "Warehouse,supply chain",
  "Website Development",
  "Telecommunication",
  "Travel and Tourism",
  "Veterinary Services",
];
